#include <stdio.h>
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
int main(){
	int last = 1;
	int answer = 2, current = 2, tmp;

	while (current < 4000000)
	{
		tmp = last;
		last = current;
		current += tmp;

		if ((current & 1) == 0){
			answer += current;
		}

	}
	printf("Answer : %i" , answer);
	return 0;
}
